'use client';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, Box, Camera, Check, Grid3x3, Rotate3d, ChevronDown, ChevronRight, CircleHelp, Eye, EyeOff, Focus, Layers3, Maximize2, Minus, Moon, MousePointer2, Pause, Play, Plus, RotateCcw, Settings, Sun, Wind, X, Orbit, Gauge, ScanLine, Crosshair } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuRadioGroup, DropdownMenuRadioItem } from '@/components/ui/dropdown-menu';
import WalkthroughCard from '@/components/engine/walkthrough-card';
import { WALKTHROUGHS, startWalkthrough, exitWalkthrough, stepWalkthrough, advanceWalkthrough } from '@/lib/engine/walkthroughs';
import SectionControls from '@/components/engine/section-controls';
import { DEFAULT_SECTION_DEPTH, DEFAULT_SECTION_PLANE } from '@/lib/engine/section-plane';
import EngineScene from '@/components/engine/engine-scene';
import type { PieceInfo } from '@/lib/engine/explosion-controller';
import { ENGINES, getParts, EngineType, ViewerState } from '@/lib/engine/engine-data';
const INITIAL:ViewerState={walkthrough:null,selectedParts:[],engine:'turbofan',mode:'assembled',explode:0,explodeLayout:'inventory',spacing:40,cycling:false,selectedPiece:null,isolatedPiece:null,section:DEFAULT_SECTION_DEPTH,sectionPlane:{...DEFAULT_SECTION_PLANE},playing:false,speed:1,flow:false,labels:false,grid:true,spin:false,hidden:[],selected:null,isolated:null,quality:'ultra',camera:'perspective',reset:0,zoom:0};
export default function Home(){
 const [s,set]=useState<ViewerState>(INITIAL),[library,setLibrary]=useState(false),[help,setHelp]=useState(false),[settings,setSettings]=useState(false),[mobileParts,setMobileParts]=useState(false),[piece,setPiece]=useState<PieceInfo|null>(null),[counts,setCounts]=useState({total:0,visible:0});
 const [theme,setTheme]=useState<'dark'|'light'>('dark');
 useEffect(()=>{try{if(localStorage.getItem('atlas-theme')==='light')setTheme('light');}catch{}},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('atlas-theme',theme);}catch{}},[theme]);
 useEffect(()=>{if(!s.cycling||s.mode!=='exploded')return;let frame=0;const started=performance.now(),phase=Math.acos(1-2*Math.max(0,Math.min(1,s.explode/100)));let last=0;const tick=(now:number)=>{if(now-last>32){const value=(1-Math.cos(phase+(now-started)/1000*s.speed*Math.PI/6))*50;set(x=>({...x,explode:value}));last=now;}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[s.cycling,s.mode,s.speed]);
 const walkthroughActive=!!s.walkthrough;
 const walkthroughButton=useRef<HTMLButtonElement>(null);
 const beginWalkthrough=()=>{set(startWalkthrough);setPiece(null);setHelp(false);setMobileParts(false);};
 const leaveWalkthrough=()=>{set(exitWalkthrough);walkthroughButton.current?.focus();};
 const toggleWalkthrough=()=>set(x=>x.walkthrough?{...x,walkthrough:{...x.walkthrough,playing:!x.walkthrough.playing}}:x);
 useEffect(()=>{
  if(!s.walkthrough?.playing||help||settings||library||mobileParts)return;
  const timer=window.setTimeout(()=>set(advanceWalkthrough),8000/s.speed);
  return()=>window.clearTimeout(timer);
 },[s.walkthrough?.station,s.walkthrough?.playing,s.speed,s.engine,help,settings,library,mobileParts]);
 useEffect(()=>{
  if(!walkthroughActive||help||settings||library||mobileParts)return;
  const keydown=(event:KeyboardEvent)=>{
   if(event.altKey||event.ctrlKey||event.metaKey||event.shiftKey)return;
   const target=event.target as HTMLElement;
   if(target.closest('input,textarea,select,[contenteditable="true"],[role="slider"],[role="combobox"],[role="menu"],[role="listbox"],[role="dialog"]'))return;
   if(event.key==='Escape'){event.preventDefault();set(exitWalkthrough);walkthroughButton.current?.focus();}
   else if(event.key==='ArrowLeft'||event.key==='ArrowRight'){event.preventDefault();set(x=>stepWalkthrough(x,event.key==='ArrowRight'?1:-1));}
   else if(event.code==='Space'){event.preventDefault();if(!event.repeat)set(x=>x.walkthrough?{...x,walkthrough:{...x.walkthrough,playing:!x.walkthrough.playing}}:x);}
  };
  window.addEventListener('keydown',keydown);return()=>window.removeEventListener('keydown',keydown);
 },[walkthroughActive,help,settings,library,mobileParts]);
 const update=(v:Partial<ViewerState>)=>set(x=>({...x,...v}));
 const explore=(v:Partial<ViewerState>)=>set(x=>({...exitWalkthrough(x),...v}));
 const station=s.walkthrough?WALKTHROUGHS[s.engine][s.walkthrough.station]:null;
 const PARTS=getParts(s.engine);const engine=ENGINES[s.engine],part=PARTS.find(p=>p.id===s.selected);
 const choose=(id:string|null,selectedPiece?:PieceInfo|null)=>{setPiece(selectedPiece??null);explore({selected:id,selectedParts:[],selectedPiece:selectedPiece?.id??null});};
 const changeMode=(mode:string)=>{setPiece(null);explore({mode,selectedParts:[],isolated:null,isolatedPiece:null,selectedPiece:null,selected:null,cycling:false,playing:false,...(mode!=='exploded'?{explode:0}:{})});};
 const scrubSeparation=(explode:number)=>{setPiece(null);explore({mode:'exploded',selectedParts:[],explode,cycling:false,playing:false,isolated:null,isolatedPiece:null,selectedPiece:null,selected:null});};
 const toggle=(id:string)=>explore({hidden:s.hidden.includes(id)?s.hidden.filter(x=>x!==id):[...s.hidden,id]});
 const changeEngine=(id:EngineType)=>{set(x=>({...INITIAL,engine:id,reset:x.reset+1,quality:x.quality,grid:x.grid,spin:x.spin,flow:x.walkthrough?.previousFlow??x.flow}));setPiece(null);setLibrary(false);};
 return <main className="atlas">
  <header className="topbar"><a className="brand" href="/" aria-label="Mechanica home"><span className="brand-icon"><Orbit size={23}/></span><span>MECHANICA</span></a><span className="header-divider"/><span className="edition">THE MECHANICAL COLLECTION</span><div className="header-right"><a className="icon-button" href="https://github.com/PouyanJay/mechanica" target="_blank" rel="noreferrer" title="Source on GitHub" aria-label="Source on GitHub"><svg width="19" height="19" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M12 .5C5.65.5.5 5.65.5 12c0 5.08 3.29 9.39 7.86 10.91.58.11.79-.25.79-.55 0-.27-.01-1.17-.02-2.12-3.2.7-3.87-1.36-3.87-1.36-.52-1.33-1.28-1.68-1.28-1.68-1.04-.71.08-.7.08-.7 1.15.08 1.76 1.19 1.76 1.19 1.03 1.76 2.7 1.25 3.35.96.1-.75.4-1.25.73-1.54-2.55-.29-5.24-1.28-5.24-5.69 0-1.26.45-2.29 1.19-3.09-.12-.29-.52-1.46.11-3.05 0 0 .97-.31 3.17 1.18a11 11 0 0 1 5.77 0c2.2-1.49 3.17-1.18 3.17-1.18.63 1.59.23 2.76.11 3.05.74.8 1.19 1.83 1.19 3.09 0 4.42-2.69 5.39-5.26 5.68.41.36.78 1.06.78 2.14 0 1.55-.01 2.79-.01 3.17 0 .31.21.67.8.55C20.22 21.38 23.5 17.08 23.5 12 23.5 5.65 18.35.5 12 .5z"/></svg></a><button className="icon-button" onClick={()=>setSettings(true)} title="Settings" aria-label="Viewer settings"><Settings size={19}/></button><button className="icon-button" onClick={()=>setHelp(true)} title="Viewer help" aria-label="Viewer help"><CircleHelp size={19}/></button></div></header>
  <div className="workbench">
   <aside className={'parts-panel '+(mobileParts?'mobile-open':'')}>
    <div className="panel-title"><span>Engine</span><button className="mobile-close icon-button" onClick={()=>setMobileParts(false)} aria-label="Close components"><X size={18}/></button></div>
    <button className="engine-picker" onClick={()=>setLibrary(true)}><span className="engine-pick-icon"><Wind size={24}/></span><span><strong>{engine.name}</strong><small>{engine.family}</small></span><ChevronDown size={17}/></button>
    <div className="sidebar-section-heading"><span>Components</span></div>
    <div className="part-list">{PARTS.map(p=><div className={'part-row '+((s.selectedParts.length?s.selectedParts.includes(p.id):s.selected===p.id)?'active':'')+(s.hidden.includes(p.id)?' muted':'')} key={p.id}>
     <button className="part-select" onClick={()=>{choose(p.id);setMobileParts(false);}}><span className="part-number">{p.number}</span><span>{p.id==='fan'&&s.engine==='turbojet'?'Inlet & guide vanes':p.name}</span></button><button className="part-eye" aria-label={(s.hidden.includes(p.id)?'Show ':'Hide ')+p.name} title={(s.hidden.includes(p.id)?'Show ':'Hide ')+p.name} onClick={()=>toggle(p.id)}>{s.hidden.includes(p.id)?<EyeOff size={15}/>:<Eye size={15}/>}</button>
    </div>)}</div>
    {(s.hidden.length>0||s.isolated||s.isolatedPiece)&&<button className="restore-all" onClick={()=>update({hidden:[],isolated:null,isolatedPiece:null})}>Show all components <RotateCcw size={14}/></button>}
    </aside>
   <section className={'viewport '+(s.mode==='exploded'?'is-exploded ':'')+(s.selected?'has-selection ':'')+(s.walkthrough?'walkthrough-active':'')} aria-label="Engine workspace">
    <EngineScene state={s} onSelect={choose} onStats={(total,visible)=>setCounts(x=>x.total===total&&x.visible===visible?x:{total,visible})}/>
    <div className="viewport-heading"><h1>{engine.name}<span> engine</span></h1><p>{engine.subtitle}</p></div>
    <button className="mobile-components" onClick={()=>setMobileParts(true)}><Layers3 size={17}/> Components</button>
    <div className="view-tools"><button onClick={()=>update({zoom:s.zoom+1})} title="Zoom in" aria-label="Zoom in"><Plus size={18}/></button><button onClick={()=>update({zoom:s.zoom-1})} title="Zoom out" aria-label="Zoom out"><Minus size={18}/></button><span/><button onClick={()=>update({reset:s.reset+1,isolated:null,isolatedPiece:null})} title="Fit view" aria-label="Fit view"><Maximize2 size={18}/></button>{s.mode!=='exploded'&&<DropdownMenu><DropdownMenuTrigger asChild><button title="Camera view" aria-label="Camera view"><Camera size={18}/></button></DropdownMenuTrigger><DropdownMenuContent side="left" align="start" sideOffset={10} className="view-menu" onCloseAutoFocus={e=>e.preventDefault()}><DropdownMenuRadioGroup value={s.camera} onValueChange={v=>update({camera:v,reset:s.reset+1})}><DropdownMenuRadioItem value="perspective">Perspective</DropdownMenuRadioItem><DropdownMenuRadioItem value="ortho">Orthographic</DropdownMenuRadioItem><DropdownMenuRadioItem value="side">Side</DropdownMenuRadioItem><DropdownMenuRadioItem value="front">Front</DropdownMenuRadioItem></DropdownMenuRadioGroup></DropdownMenuContent></DropdownMenu>}<button onClick={()=>update({labels:!s.labels})} className={s.labels?'on':''} title="Component labels" aria-label="Toggle component labels" aria-pressed={s.labels}><MousePointer2 size={18}/></button><button onClick={()=>update({grid:!s.grid})} className={s.grid?'on':''} title="Floor grid" aria-label="Toggle floor grid" aria-pressed={s.grid}><Grid3x3 size={18}/></button><button onClick={()=>update({spin:!s.spin})} className={s.spin?'on':''} title="Auto-rotate" aria-label="Toggle auto-rotate" aria-pressed={s.spin}><Rotate3d size={18}/></button></div>
    {(s.isolated||s.isolatedPiece)&&<button className="isolation-pill" onClick={()=>update({isolated:null,isolatedPiece:null})}><Focus size={14}/> Isolating {s.isolatedPiece?piece?.name:PARTS.find(p=>p.id===s.isolated)?.short}<X size={14}/></button>}
    {part&&!s.walkthrough&&<div className="part-detail" role="region" aria-label="Selected component"><div className="detail-header"><span><i style={{background:part.color}}/>{part.number}</span><button className="icon-button" onClick={()=>choose(null)} aria-label="Close component details"><X size={17}/></button></div><h2>{piece?piece.name:part.id==='fan'&&s.engine==='turbojet'?'Inlet & guide vanes':part.name}</h2>{piece&&<p className='piece-parent'>{part.name}</p>}<p className="detail-role">{part.role}</p><p>{s.engine==='turbojet'&&part.id==='fan'?'The inlet guides incoming air toward the axial compressor. This turbojet has no separate bypass fan.':s.engine==='turbojet'&&part.id==='shaft'?'A single spool connects the turbine to the compressor. Bearings support the shaft as it transmits torque through the engine core.':part.description}</p><div className="detail-material"><span>MATERIAL</span><strong>{part.material}</strong></div><button className="isolate-button" onClick={()=>update(piece?{isolatedPiece:s.isolatedPiece===piece.id?null:piece.id,isolated:null,hidden:s.hidden.filter(x=>x!==part.id),cycling:false}:{isolated:s.isolated===part.id?null:part.id,isolatedPiece:null,hidden:s.hidden.filter(x=>x!==part.id),cycling:false})}><Focus size={16}/>{(s.isolated===part.id||s.isolatedPiece===piece?.id)?'Show all pieces':piece?'Isolate this piece':'Isolate component'}<ChevronRight size={16}/></button></div>}
    {station&&s.walkthrough&&<WalkthroughCard station={station} componentNames={station.parts.map(id=>PARTS.find(p=>p.id===id)!.name)} index={s.walkthrough.station} total={WALKTHROUGHS[s.engine].length} playing={s.walkthrough.playing} onPrevious={()=>set(x=>stepWalkthrough(x,-1))} onNext={()=>set(x=>stepWalkthrough(x,1))} onTogglePlaying={toggleWalkthrough} onExit={leaveWalkthrough}/>}
    <div className="bottom-console">
     <div className="master-explode-control">
      <div className="master-explode-heading"><label id="explode-engine-label">Separation</label><output aria-live="off">{Math.round(s.explode)}<span>%</span></output><button title="Assemble and reset" aria-label="Assemble and reset separation" onClick={()=>scrubSeparation(0)}><RotateCcw size={17}/></button></div>
      <Slider aria-labelledby="explode-engine-label" aria-valuetext={`${Math.round(s.explode)} percent separated`} min={0} max={100} step={0.1} value={[s.explode]} onValueChange={([value])=>scrubSeparation(value)}/>
      </div>
     <div className="console-main"><Tabs value={s.mode} onValueChange={changeMode}><TabsList aria-label="Engine view mode" className="mode-tabs"><TabsTrigger value="assembled"><Box size={16}/><span>Assembled</span></TabsTrigger><TabsTrigger value="cutaway"><ScanLine size={16}/><span>Cutaway</span></TabsTrigger><TabsTrigger value="exploded"><Layers3 size={16}/><span>Explore</span></TabsTrigger></TabsList></Tabs><span className="console-divider"/><button className={'play-button '+((s.walkthrough?s.walkthrough.playing:s.mode==='exploded'?s.cycling:s.playing)?'playing':'')} title={s.walkthrough?'Play or pause walkthrough':s.mode==='exploded'?'Cycle separation and reassembly':'Animate engine rotation'} aria-label={s.walkthrough?(s.walkthrough.playing?'Pause walkthrough from console':'Play walkthrough from console'):s.mode==='exploded'?(s.cycling?'Pause separation cycle':'Cycle separation and reassembly'):(s.playing?'Pause engine rotation':'Animate engine rotation')} onClick={()=>s.walkthrough?toggleWalkthrough():update(s.mode==='exploded'?{cycling:!s.cycling}:{playing:!s.playing})}>{(s.walkthrough?s.walkthrough.playing:s.mode==='exploded'?s.cycling:s.playing)?<Pause size={16} fill="currentColor"/>:<Play size={16} fill="currentColor"/>}</button><Select value={String(s.speed)} onValueChange={v=>update({speed:Number(v)})}><SelectTrigger className="speed-select" aria-label="Animation speed"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="0.25">0.25×</SelectItem><SelectItem value="0.5">0.5×</SelectItem><SelectItem value="1">1×</SelectItem><SelectItem value="2">2×</SelectItem></SelectContent></Select><button ref={walkthroughButton} className="walkthrough-launch" aria-pressed={!!s.walkthrough} onClick={s.walkthrough?leaveWalkthrough:beginWalkthrough}><Play size={15}/>{s.walkthrough?'Exit walkthrough':'Walkthrough'}</button><span className="console-spacer"/>{engine.flow&&<label className="flow-toggle"><Wind size={17}/><span>Airflow</span><Switch aria-label="Show illustrative airflow" title="Show illustrative flow" checked={s.flow} disabled={!!s.walkthrough||s.mode==='exploded'||!!s.isolated} onCheckedChange={v=>update({flow:v})}/></label>}</div>
     <div className="explosion-settings">
      <Select value={s.explodeLayout} onValueChange={v=>update({explodeLayout:v as 'radial'|'inventory',cycling:false})}><SelectTrigger className="explosion-layout-select" aria-label="Explosion layout"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="inventory">All pieces</SelectItem><SelectItem value="radial">Radial spread</SelectItem></SelectContent></Select>
      <label className="spacing-control"><span>Spacing</span><Slider aria-label="Space between pieces" min={0} max={100} step={1} value={[s.spacing]} onValueChange={([spacing])=>update({spacing,cycling:false})}/></label><span className="piece-count">{counts.visible.toLocaleString()} {counts.visible===1?'piece':'pieces'}</span>
     </div>
     {s.mode==='cutaway'&&<SectionControls depth={s.section} plane={s.sectionPlane} onDepthChange={section=>update({section})} onPlaneChange={sectionPlane=>update({sectionPlane})} onReset={()=>update({section:DEFAULT_SECTION_DEPTH,sectionPlane:{...DEFAULT_SECTION_PLANE}})}/>}

    </div>
    </section>
  </div>
  <Dialog open={library} onOpenChange={setLibrary}><DialogContent className="library-dialog"><DialogTitle>Engine collection</DialogTitle><DialogDescription>Explore different engine architectures.</DialogDescription>{['Aircraft turbines','Piston engines','Rotary engines'].map(family=><div className="engine-family" key={family}><div className="library-category">{family}</div>{(Object.entries(ENGINES) as [EngineType,typeof engine][]).filter(([,e])=>e.family===family).map(([id,e])=><button key={id} className={'library-engine '+(id===s.engine?'chosen':'')} onClick={()=>changeEngine(id)}><span className="library-engine-icon">{e.family==='Aircraft turbines'?<Wind size={29}/>:e.family==='Piston engines'?<Gauge size={29}/>:<Orbit size={29}/>}</span><span><strong>{e.name}</strong><small>{e.subtitle}</small></span>{id===s.engine?<Check size={20}/>:<ChevronRight size={20}/>}</button>)}</div>)}<p className="library-footnote">Seven original educational models. Each has its own components, mechanism and individual-piece separation.</p></DialogContent></Dialog>
  <Dialog open={help} onOpenChange={setHelp}><DialogContent className="help-dialog"><DialogTitle>Explore the engine</DialogTitle><DialogDescription>Mechanica · Reference collection</DialogDescription><div className="help-row"><Play/><p><strong>Follow the working fluid</strong>Take a guided walkthrough of this engine. Use Left and Right to step, Space to pause or play, and Escape to exit. The speed control sets the pace.<button className="walkthrough-launch" onClick={beginWalkthrough}>Start walkthrough</button></p></div><div className="help-row"><Orbit/><p><strong>Move around</strong>Drag with one finger or the left mouse button. Pinch or scroll to zoom. Use two fingers or the right mouse button to pan.</p></div><div className="help-row"><Crosshair/><p><strong>Look inside</strong>Choose Cutaway and adjust section depth. Open Plane controls to rotate the cut, choose an orientation, show the plane, or flip the removed side. Click a component or use the component list, then isolate it for a closer look.</p></div><div className="help-row"><Layers3/><p><strong>Take it apart</strong>Drag the Explode engine slider. At 0% the engine is fully assembled. The first part of the slider opens up the assembly; dragging farther spreads the individual pieces into an inventory. Stop anywhere to inspect that exact stage. Drag back to 0% to reassemble. Layout and spacing controls let you adjust the spread.</p></div><div className="model-note"><strong>About the geometry</strong><p>Original parametric educational models of four aircraft turbine architectures, a cross-plane V8, an inline-four and a single-rotor Wankel engine. These are generic architectures, not replicas of a specific manufacturer's engine. Stage counts, proportions, valve timing and surface details are illustrative. Piston linkage lengths are constrained; the rotary shaft turns three times per rotor revolution. Playback is slowed for inspection; airflow is schematic, not a CFD result.</p><a href="https://www.grc.nasa.gov/www/k-12/airplane/aturbf.html" target="_blank" rel="noreferrer">Engine principles: NASA Glenn <ArrowUpRight size={14}/></a></div></DialogContent></Dialog>
  <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="settings-dialog"><DialogTitle>Settings</DialogTitle><DialogDescription>Viewer preferences. Saved on this device.</DialogDescription>
   <div className="setting-row"><div className="setting-copy"><strong>Appearance</strong><small>Canvas and panel theme</small></div><div className="theme-seg" role="group" aria-label="Theme"><button className={theme==='dark'?'active':''} aria-pressed={theme==='dark'} onClick={()=>setTheme('dark')}><Moon size={15}/>Dark</button><button className={theme==='light'?'active':''} aria-pressed={theme==='light'} onClick={()=>setTheme('light')}><Sun size={15}/>Light</button></div></div>
   <div className="setting-row"><div className="setting-copy"><strong>Component labels</strong><small>Name tags over the model</small></div><Switch aria-label="Component labels" checked={s.labels} onCheckedChange={v=>update({labels:v})}/></div>
   <div className="setting-row"><div className="setting-copy"><strong>Rendering quality</strong><small>Balanced saves battery</small></div><Select value={s.quality} onValueChange={v=>update({quality:v})}><SelectTrigger className="settings-quality" aria-label="Rendering quality"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ultra">Ultra</SelectItem><SelectItem value="balanced">Balanced</SelectItem></SelectContent></Select></div>
  </DialogContent></Dialog>
 </main>;
}
