'use client';
import { useEffect, useState } from 'react';
import { ArrowUpRight, Box, Camera, Check, Grid3x3, ChevronDown, ChevronRight, CircleHelp, Eye, EyeOff, Focus, Layers3, Maximize2, Minus, Moon, MousePointer2, Pause, Play, Plus, RotateCcw, Settings, Sun, Wind, X, Orbit, Gauge, ScanLine, Crosshair } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Switch } from '@/components/ui/switch';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { DropdownMenu, DropdownMenuTrigger, DropdownMenuContent, DropdownMenuRadioGroup, DropdownMenuRadioItem } from '@/components/ui/dropdown-menu';
import EngineScene from './engine-scene';
import type { PieceInfo } from './explosion-controller';
import { ENGINES, getParts, EngineType, ViewerState } from './engine-data';
const INITIAL:ViewerState={engine:'turbofan',mode:'assembled',explode:0,explodeLayout:'inventory',spacing:40,cycling:false,selectedPiece:null,isolatedPiece:null,section:52,playing:false,speed:1,flow:false,labels:false,grid:true,hidden:[],selected:null,isolated:null,quality:'ultra',camera:'perspective',reset:0,zoom:0};
export default function Home(){
 const [s,set]=useState<ViewerState>(INITIAL),[library,setLibrary]=useState(false),[help,setHelp]=useState(false),[settings,setSettings]=useState(false),[mobileParts,setMobileParts]=useState(false),[piece,setPiece]=useState<PieceInfo|null>(null),[counts,setCounts]=useState({total:0,visible:0});
 const [theme,setTheme]=useState<'dark'|'light'>('dark');
 useEffect(()=>{try{if(localStorage.getItem('atlas-theme')==='light')setTheme('light');}catch{}},[]);
 useEffect(()=>{document.documentElement.dataset.theme=theme;try{localStorage.setItem('atlas-theme',theme);}catch{}},[theme]);
 useEffect(()=>{if(!s.cycling||s.mode!=='exploded')return;let frame=0;const started=performance.now(),phase=Math.acos(1-2*Math.max(0,Math.min(1,s.explode/100)));let last=0;const tick=(now:number)=>{if(now-last>32){const value=(1-Math.cos(phase+(now-started)/1000*s.speed*Math.PI/6))*50;set(x=>({...x,explode:value}));last=now;}frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[s.cycling,s.mode,s.speed]);
 const update=(v:Partial<ViewerState>)=>set(x=>({...x,...v}));
 const PARTS=getParts(s.engine);const engine=ENGINES[s.engine],part=PARTS.find(p=>p.id===s.selected);
 const choose=(id:string|null,selectedPiece?:PieceInfo|null)=>{setPiece(selectedPiece??null);update({selected:id,selectedPiece:selectedPiece?.id??null});};
 const changeMode=(mode:string)=>{setPiece(null);update({mode,isolated:null,isolatedPiece:null,selectedPiece:null,selected:null,cycling:false,playing:false,...(mode!=='exploded'?{explode:0}:{})});};
 const scrubSeparation=(explode:number)=>{setPiece(null);update({mode:'exploded',explode,cycling:false,playing:false,isolated:null,isolatedPiece:null,selectedPiece:null,selected:null});};
 const toggle=(id:string)=>update({hidden:s.hidden.includes(id)?s.hidden.filter(x=>x!==id):[...s.hidden,id]});
 const changeEngine=(id:EngineType)=>{set(x=>({...INITIAL,engine:id,reset:x.reset+1,quality:x.quality,grid:x.grid}));setPiece(null);setLibrary(false);};
 return <main className="atlas">
  <header className="topbar"><a className="brand" href="/" aria-label="Mechanica home"><span className="brand-icon"><Orbit size={23}/></span><span>MECHANICA</span></a><span className="header-divider"/><span className="edition">THE MECHANICAL COLLECTION</span><div className="header-right"><button className="icon-button" onClick={()=>setSettings(true)} title="Settings" aria-label="Viewer settings"><Settings size={19}/></button><button className="icon-button" onClick={()=>setHelp(true)} title="Viewer help" aria-label="Viewer help"><CircleHelp size={19}/></button></div></header>
  <div className="workbench">
   <aside className={'parts-panel '+(mobileParts?'mobile-open':'')}>
    <div className="panel-title"><span>Engine</span><button className="mobile-close icon-button" onClick={()=>setMobileParts(false)} aria-label="Close components"><X size={18}/></button></div>
    <button className="engine-picker" onClick={()=>setLibrary(true)}><span className="engine-pick-icon"><Wind size={24}/></span><span><strong>{engine.name}</strong><small>{engine.family}</small></span><ChevronDown size={17}/></button>
    <div className="sidebar-section-heading"><span>Components</span></div>
    <div className="part-list">{PARTS.map(p=><div className={'part-row '+(s.selected===p.id?'active':'')+(s.hidden.includes(p.id)?' muted':'')} key={p.id}>
     <button className="part-select" onClick={()=>{choose(p.id);setMobileParts(false);}}><span className="part-number">{p.number}</span><span>{p.id==='fan'&&s.engine==='turbojet'?'Inlet & guide vanes':p.name}</span></button><button className="part-eye" aria-label={(s.hidden.includes(p.id)?'Show ':'Hide ')+p.name} title={(s.hidden.includes(p.id)?'Show ':'Hide ')+p.name} onClick={()=>toggle(p.id)}>{s.hidden.includes(p.id)?<EyeOff size={15}/>:<Eye size={15}/>}</button>
    </div>)}</div>
    {(s.hidden.length>0||s.isolated||s.isolatedPiece)&&<button className="restore-all" onClick={()=>update({hidden:[],isolated:null,isolatedPiece:null})}>Show all components <RotateCcw size={14}/></button>}
    </aside>
   <section className={'viewport '+(s.mode==='exploded'?'is-exploded ':'')+(s.selected?'has-selection':'')} aria-label="Engine workspace">
    <EngineScene state={s} onSelect={choose} onStats={(total,visible)=>setCounts(x=>x.total===total&&x.visible===visible?x:{total,visible})}/>
    <div className="viewport-heading"><h1>{engine.name}<span> engine</span></h1><p>{engine.subtitle}</p></div>
    <button className="mobile-components" onClick={()=>setMobileParts(true)}><Layers3 size={17}/> Components</button>
    <div className="view-tools"><button onClick={()=>update({zoom:s.zoom+1})} title="Zoom in" aria-label="Zoom in"><Plus size={18}/></button><button onClick={()=>update({zoom:s.zoom-1})} title="Zoom out" aria-label="Zoom out"><Minus size={18}/></button><span/><button onClick={()=>update({reset:s.reset+1,isolated:null,isolatedPiece:null})} title="Fit view" aria-label="Fit view"><Maximize2 size={18}/></button>{s.mode!=='exploded'&&<DropdownMenu><DropdownMenuTrigger asChild><button title="Camera view" aria-label="Camera view"><Camera size={18}/></button></DropdownMenuTrigger><DropdownMenuContent side="left" align="start" sideOffset={10} className="view-menu" onCloseAutoFocus={e=>e.preventDefault()}><DropdownMenuRadioGroup value={s.camera} onValueChange={v=>update({camera:v,reset:s.reset+1})}><DropdownMenuRadioItem value="perspective">Perspective</DropdownMenuRadioItem><DropdownMenuRadioItem value="ortho">Orthographic</DropdownMenuRadioItem><DropdownMenuRadioItem value="side">Side</DropdownMenuRadioItem><DropdownMenuRadioItem value="front">Front</DropdownMenuRadioItem></DropdownMenuRadioGroup></DropdownMenuContent></DropdownMenu>}<button onClick={()=>update({labels:!s.labels})} className={s.labels?'on':''} title="Component labels" aria-label="Toggle component labels" aria-pressed={s.labels}><MousePointer2 size={18}/></button><button onClick={()=>update({grid:!s.grid})} className={s.grid?'on':''} title="Floor grid" aria-label="Toggle floor grid" aria-pressed={s.grid}><Grid3x3 size={18}/></button></div>
    {(s.isolated||s.isolatedPiece)&&<button className="isolation-pill" onClick={()=>update({isolated:null,isolatedPiece:null})}><Focus size={14}/> Isolating {s.isolatedPiece?piece?.name:PARTS.find(p=>p.id===s.isolated)?.short}<X size={14}/></button>}
    {part&&<div className="part-detail" role="region" aria-label="Selected component"><div className="detail-header"><span><i style={{background:part.color}}/>{part.number}</span><button className="icon-button" onClick={()=>choose(null)} aria-label="Close component details"><X size={17}/></button></div><h2>{piece?piece.name:part.id==='fan'&&s.engine==='turbojet'?'Inlet & guide vanes':part.name}</h2>{piece&&<p className='piece-parent'>{part.name}</p>}<p className="detail-role">{part.role}</p><p>{s.engine==='turbojet'&&part.id==='fan'?'The inlet guides incoming air toward the axial compressor. This turbojet has no separate bypass fan.':s.engine==='turbojet'&&part.id==='shaft'?'A single spool connects the turbine to the compressor. Bearings support the shaft as it transmits torque through the engine core.':part.description}</p><div className="detail-material"><span>MATERIAL</span><strong>{part.material}</strong></div><button className="isolate-button" onClick={()=>update(piece?{isolatedPiece:s.isolatedPiece===piece.id?null:piece.id,isolated:null,hidden:s.hidden.filter(x=>x!==part.id),cycling:false}:{isolated:s.isolated===part.id?null:part.id,isolatedPiece:null,hidden:s.hidden.filter(x=>x!==part.id),cycling:false})}><Focus size={16}/>{(s.isolated===part.id||s.isolatedPiece===piece?.id)?'Show all pieces':piece?'Isolate this piece':'Isolate component'}<ChevronRight size={16}/></button></div>}
    <div className="bottom-console">
     <div className="master-explode-control">
      <div className="master-explode-heading"><label id="explode-engine-label">Explode engine</label><output aria-live="off">{Math.round(s.explode)}<span>%</span></output><button title="Assemble and reset" aria-label="Assemble and reset separation" onClick={()=>scrubSeparation(0)}><RotateCcw size={17}/></button></div>
      <Slider aria-labelledby="explode-engine-label" aria-valuetext={`${Math.round(s.explode)} percent separated`} min={0} max={100} step={0.1} value={[s.explode]} onValueChange={([value])=>scrubSeparation(value)}/>
      </div>
     <div className="console-main"><Tabs value={s.mode} onValueChange={changeMode}><TabsList aria-label="Engine view mode" className="mode-tabs"><TabsTrigger value="assembled"><Box size={16}/><span>Assembled</span></TabsTrigger><TabsTrigger value="cutaway"><ScanLine size={16}/><span>Cutaway</span></TabsTrigger><TabsTrigger value="exploded"><Layers3 size={16}/><span>Explore</span></TabsTrigger></TabsList></Tabs><span className="console-divider"/><button className={'play-button '+((s.mode==='exploded'?s.cycling:s.playing)?'playing':'')} title={s.mode==='exploded'?'Cycle separation and reassembly':'Animate engine rotation'} aria-label={s.mode==='exploded'?(s.cycling?'Pause separation cycle':'Cycle separation and reassembly'):(s.playing?'Pause engine rotation':'Animate engine rotation')} onClick={()=>update(s.mode==='exploded'?{cycling:!s.cycling}:{playing:!s.playing})}>{(s.mode==='exploded'?s.cycling:s.playing)?<Pause size={16} fill="currentColor"/>:<Play size={16} fill="currentColor"/>}</button><Select value={String(s.speed)} onValueChange={v=>update({speed:Number(v)})}><SelectTrigger className="speed-select" aria-label="Animation speed"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="0.25">0.25×</SelectItem><SelectItem value="0.5">0.5×</SelectItem><SelectItem value="1">1×</SelectItem><SelectItem value="2">2×</SelectItem></SelectContent></Select><span className="console-spacer"/>{engine.flow&&<label className="flow-toggle"><Wind size={17}/><span>Airflow</span><Switch aria-label="Show illustrative airflow" title="Show illustrative flow" checked={s.flow} disabled={s.mode==='exploded'||!!s.isolated} onCheckedChange={v=>update({flow:v})}/></label>}</div>
     <div className="explosion-settings">
      <Select value={s.explodeLayout} onValueChange={v=>update({explodeLayout:v as 'radial'|'inventory',cycling:false})}><SelectTrigger className="explosion-layout-select" aria-label="Explosion layout"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="inventory">All pieces</SelectItem><SelectItem value="radial">Radial spread</SelectItem></SelectContent></Select>
      <label className="spacing-control"><span>Spacing</span><Slider aria-label="Space between pieces" min={0} max={100} step={1} value={[s.spacing]} onValueChange={([spacing])=>update({spacing,cycling:false})}/></label><span className="piece-count">{counts.visible.toLocaleString()} {counts.visible===1?'piece':'pieces'}</span>
     </div>
     {s.mode==='cutaway'&&<div className="console-slider"><span>Section depth</span><Slider aria-label="Section depth" value={[s.section]} min={0} max={100} step={1} onValueChange={([section])=>update({section})}/><output>{Math.round(s.section)}%</output></div>}

    </div>
    </section>
  </div>
  <Dialog open={library} onOpenChange={setLibrary}><DialogContent className="library-dialog"><DialogTitle>Engine collection</DialogTitle><DialogDescription>Explore different engine architectures.</DialogDescription>{['Aircraft turbines','Piston engines','Rotary engines'].map(family=><div className="engine-family" key={family}><div className="library-category">{family}</div>{(Object.entries(ENGINES) as [EngineType,typeof engine][]).filter(([,e])=>e.family===family).map(([id,e])=><button key={id} className={'library-engine '+(id===s.engine?'chosen':'')} onClick={()=>changeEngine(id)}><span className="library-engine-icon">{e.family==='Aircraft turbines'?<Wind size={29}/>:e.family==='Piston engines'?<Gauge size={29}/>:<Orbit size={29}/>}</span><span><strong>{e.name}</strong><small>{e.subtitle}</small></span>{id===s.engine?<Check size={20}/>:<ChevronRight size={20}/>}</button>)}</div>)}<p className="library-footnote">Seven original educational models. Each has its own components, mechanism and individual-piece separation.</p></DialogContent></Dialog>
  <Dialog open={help} onOpenChange={setHelp}><DialogContent className="help-dialog"><DialogTitle>Explore the engine</DialogTitle><DialogDescription>Mechanica · Reference collection</DialogDescription><div className="help-row"><Orbit/><p><strong>Move around</strong>Drag with one finger or the left mouse button. Pinch or scroll to zoom. Use two fingers or the right mouse button to pan.</p></div><div className="help-row"><Crosshair/><p><strong>Look inside</strong>Choose Cutaway and adjust section depth. Click a component or use the component list, then isolate it for a closer look.</p></div><div className="help-row"><Layers3/><p><strong>Take it apart</strong>Drag the Explode engine slider. At 0% the engine is fully assembled. The first part of the slider opens up the assembly; dragging farther spreads the individual pieces into an inventory. Stop anywhere to inspect that exact stage. Drag back to 0% to reassemble. Layout and spacing controls let you adjust the spread.</p></div><div className="model-note"><strong>About the geometry</strong><p>Original parametric educational models of four aircraft turbine architectures, a cross-plane V8, an inline-four and a single-rotor Wankel engine. These are generic architectures, not replicas of a specific manufacturer's engine. Stage counts, proportions, valve timing and surface details are illustrative. Piston linkage lengths are constrained; the rotary shaft turns three times per rotor revolution. Playback is slowed for inspection; airflow is schematic, not a CFD result.</p><a href="https://www.grc.nasa.gov/www/k-12/airplane/aturbf.html" target="_blank" rel="noreferrer">Engine principles: NASA Glenn <ArrowUpRight size={14}/></a></div></DialogContent></Dialog>
  <Dialog open={settings} onOpenChange={setSettings}><DialogContent className="settings-dialog"><DialogTitle>Settings</DialogTitle><DialogDescription>Viewer preferences. Saved on this device.</DialogDescription>
   <div className="setting-row"><div className="setting-copy"><strong>Appearance</strong><small>Canvas and panel theme</small></div><div className="theme-seg" role="group" aria-label="Theme"><button className={theme==='dark'?'active':''} aria-pressed={theme==='dark'} onClick={()=>setTheme('dark')}><Moon size={15}/>Dark</button><button className={theme==='light'?'active':''} aria-pressed={theme==='light'} onClick={()=>setTheme('light')}><Sun size={15}/>Light</button></div></div>
   <div className="setting-row"><div className="setting-copy"><strong>Component labels</strong><small>Name tags over the model</small></div><Switch aria-label="Component labels" checked={s.labels} onCheckedChange={v=>update({labels:v})}/></div>
   <div className="setting-row"><div className="setting-copy"><strong>Rendering quality</strong><small>Balanced saves battery</small></div><Select value={s.quality} onValueChange={v=>update({quality:v})}><SelectTrigger className="settings-quality" aria-label="Rendering quality"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ultra">Ultra</SelectItem><SelectItem value="balanced">Balanced</SelectItem></SelectContent></Select></div>
  </DialogContent></Dialog>
 </main>;
}
